### ISSUE TITLE
PUBLIC_FIREBASE_CONFIG is exposed publicly

### ISSUE THREAD

**Issue by robthepaper** [jacobbowdoin/sveltefirets#13]
Hi,
is it normal that PUBLIC_FIREBASE_CONFIG is visible in the website sources when deployed in production?
Isn't it a security issue?

**Comment by jacob-8** [comment]
The config is designed for client side use and there is no way to use Firebase client side without the firebase config being exposed.  **Your security will lie in your security rules.** As recommended in the [Firebase launch checklist](https://firebase.google.com/support/guides/launch-checklist) I have a production config that is restricted to just my production domain, but even this doesn't keep someone from going there and using the console to make whatevern database calls they want.

Read https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public and https://stackoverflow.com/questions/35418143/how-to-restrict-firebase-data-modification

In your backend, if you happen to use Firebase Admin with the key for that - that is the type of thing you absolutely do not want to expose as it gives full access to your entire project. I use both Firebase Admin on the backend, and Firebase client in the frontend but haven't integrated that into the demo here. I will do that at some point, as it's very useful with SvelteKit's api routes. Much, much more convenient than Firebase functions.

**Comment by robthepaper** [comment]
Hi thanks for your detailed answer.
I will have a look at all this.
Yes indeed, i'm also using Firebase Admin in the backend, using it with Auth.js with the FirestoreAdapter to create documents for new users.

So how did you end up securing your app? did you go with security rules using request.auth then?
