### ISSUE TITLE
Message API endpoint is broken

### ISSUE THREAD

**Issue by fredguth** [jacobbowdoin/sveltefirets#7]
In KitchenSink, when clicking in "Preload firestore data for all messages in the client" link (or any other that uses api/messages) there is an error: `Not found: /messages` 
Noticed it is using 'get' instead of 'GET'.

**Comment by fredguth** [comment]
Any idea on this error?

**Comment by jacob-8** [comment]
> Any idea on this error?

I'm waiting a week or so until the recent kit changes finish up, then I'll update the routes and endpoints accordingly.

**Comment by fredguth** [comment]
:+1: He just merged the PR.

**Comment by jacob-8** [comment]
> 👍 He just merged the PR.

With bugs in `svelte-migrate` not allowing an easy transition quite yet - waiting a week will save me a lot of time trying to debug.

**Comment by jacob-8** [comment]
Updated: https://sveltefirets.vercel.app/messages
