### ISSUE TITLE
Not a issue, but a question about your project (comparating it to another solution) #76

### ISSUE THREAD

**Issue by ghost** [jacobbowdoin/sveltefirets#8]
Hi,
I would like to ask/understand, if there is a major difference in features offered by your lib, comparated to this one:
https://firelordjs.com/

Thanks you,

**Comment by jacob-8** [comment]
This project is easy to drop into a Svelte app and makes it effortless to use Firestone server and client side. It also includes the ability to use types for type safety and intellisense.

At a quick glance, FireLordJS is framework agnostic, doesn't offer convenient Svelte initialization nor components but is more comprehensive in its type offerings.
