### ISSUE TITLE
[NOT AN ISSUE] Very great project!

### ISSUE THREAD

**Issue by zanhk** [jacobbowdoin/sveltefirets#9]
Sorry for the non issue.

I just took a look at the documentation and is very well made.

I would suggest to add a donation button so people can support your work. Keep it up!

**Comment by jacob-8** [comment]
Thanks! I just added a simple PayPal button.

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://paypal.me/jacobbowdoin)
